eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8777/eureka/

name:
  value: clinic

spring:
  application:
    name: order-service  
  sleuth:
    sampler:
      probability: 1
  h2:
    console:
      enabled: true

logstash:
  host: localhost
  port: 5000
  queue-size: 512

management:
  endpoints:
    web:
      exposure:
        include: "*"
